import type { Lang } from "@/contexts/LocaleContext";

export const durationText: Record<Lang, (months: number) => string> = {
  ar: (months) => months === 12 ? "سنة كاملة" : `${months} أشهر`,
  en: (months) => months === 12 ? "1 year" : `${months} months`,
  he: (months) => months === 12 ? "שנה אחת" : `${months} חודשים`,
  ru: (months) => months === 12 ? "1 год" : `${months} месяцев`,
  uk: (months) => months === 12 ? "1 рік" : `${months} місяців`
};

export const planNames: Record<Lang, Record<string, string>> = {
  ar: { monthly: "شهر واحد", quarterly: "3 أشهر", semiannual: "6 أشهر", annual: "سنة كاملة" },
  en: { monthly: "1 month", quarterly: "3 months", semiannual: "6 months", annual: "1 year" },
  he: { monthly: "חודש אחד", quarterly: "3 חודשים", semiannual: "6 חודשים", annual: "שנה אחת" },
  ru: { monthly: "1 месяц", quarterly: "3 месяца", semiannual: "6 месяцев", annual: "1 год" },
  uk: { monthly: "1 місяць", quarterly: "3 місяці", semiannual: "6 місяців", annual: "1 рік" }
};

type Copy = {
  home: string; selectedPlan: string; accessDuration: string; keyUnique: string; planLocked: string; keyHint: string;
  buyTitle: string; buyIntro: string; contactWhatsapp: string; whatsappMessage: string; choosePayment: string; paymentIntro: string; paypal: string; bit: string; paymentOpening: string; paymentPending: string; paymentPendingHint: string; paymentFailed: string; orActivate: string; activationKey: string; proofTitle: string; proofIntro: string; amount: string; paymentStatus: string; proofSubmitted: string; proofRejected: string; proofSubmittedHint: string; chooseProof: string; proofFormats: string; proofReading: string; proofUploading: string; proofManualOnly: string; proofFileType: string; proofFileSize: string; proofRequestMissing: string; proofReadFailed: string; proofUploadFailed: string; account: string;
  keyPlaceholder: string; activationHint: string; invalidKey: string; activationSuccess: string; activating: string; activate: string;
};

export const checkoutCopy: Record<Lang, Copy> = {
  ar: { home: "الرئيسية", selectedPlan: "الخطة المختارة", accessDuration: "مدة الوصول", keyUnique: "مفتاح فريد لا يُعاد استخدامه", planLocked: "المفتاح صالح لهذه الخطة فقط", keyHint: "مفتاح تفعيل من 56 رمزاً", buyTitle: "شراء أو تفعيل المفتاح", buyIntro: "لشراء مفتاح جديد، تواصل معنا عبر WhatsApp أو اختر طريقة دفع. إذا كان لديك مفتاح لهذه الخطة، أدخله لتفعيل اشتراكك.", choosePayment: "اختر طريقة الدفع", paymentIntro: "بعد فتح رابط الدفع، سيبقى طلبك بانتظار تأكيد الدفع اليدوي. لن يتم تفعيل الاشتراك تلقائياً.", paypal: "الدفع عبر PayPal", bit: "الدفع عبر bit", paymentOpening: "جارٍ تجهيز طلب الدفع…", paymentPending: "بانتظار تأكيد الدفع", paymentPendingHint: "تم تسجيل طلبك. افتح رابط الدفع وأكمل العملية، ثم أرسل إثبات الدفع عند الحاجة. سيتم التفعيل بعد المراجعة فقط.", paymentFailed: "تعذر إنشاء طلب الدفع. حاول مرة أخرى.", contactWhatsapp: "تواصل عبر WhatsApp لشراء المفتاح", whatsappMessage: "مرحباً، أريد شراء مفتاح DAR.EST لخطة", orActivate: "لدي مفتاح بالفعل", activationKey: "مفتاح التفعيل", keyPlaceholder: "أدخل 56 حرفاً ورقماً", activationHint: "لا تشارك مفتاحك مع أي شخص. بعد نجاح التفعيل يصبح مرتبطاً بحسابك ولا يمكن نقله.", invalidKey: "أدخل مفتاحاً صحيحاً من 56 حرفاً ورقماً.", activationSuccess: "تم تفعيل الاشتراك بنجاح. سيتم فتح حسابك الآن.", activating: "جارٍ التفعيل…", activate: "تفعيل الاشتراك", proofTitle: "تأكيد الدفع", proofIntro: "ارفع صورة إيصال التحويل المرتبط بطلبك. سيبقى الاشتراك بانتظار المراجعة ولن يتم تفعيله تلقائياً.", amount: "المبلغ", paymentStatus: "حالة الطلب", proofSubmitted: "تم إرسال الإيصال للمراجعة", proofRejected: "الطلب يحتاج إجراء", proofSubmittedHint: "سيراجع فريقنا الإيصال يدوياً. سيتم تفعيل الاشتراك فقط بعد التأكيد.", chooseProof: "اختر صورة الإيصال", proofFormats: "PNG أو JPG أو PDF — الحد الأقصى 5MB", proofReading: "جارٍ قراءة الملف…", proofUploading: "جارٍ رفع الإيصال…", proofManualOnly: "التفعيل يتم بعد المراجعة اليدوية", proofFileType: "اختر صورة PNG أو JPG أو ملف PDF.", proofFileSize: "حجم الملف يتجاوز 5MB.", proofRequestMissing: "تعذر العثور على طلب الدفع.", proofReadFailed: "تعذر قراءة الملف.", proofUploadFailed: "تعذر رفع الإيصال. حاول مرة أخرى.", account: "الحساب" },
  en: { home: "Home", selectedPlan: "Selected plan", accessDuration: "Access duration", keyUnique: "Unique key, single use only", planLocked: "Key is valid for this plan only", keyHint: "56-character activation key", buyTitle: "Buy or activate your key", buyIntro: "To buy a new key, contact us on WhatsApp or choose a payment method. If you already have a key for this plan, enter it to activate your subscription.", choosePayment: "Choose a payment method", paymentIntro: "After opening the payment link, your request remains pending manual confirmation. Your subscription will not activate automatically.", paypal: "Pay with PayPal", bit: "Pay with bit", paymentOpening: "Preparing payment request…", paymentPending: "Awaiting payment confirmation", paymentPendingHint: "Your request was recorded. Open the payment link and complete payment; activation happens only after review.", paymentFailed: "Could not create the payment request. Please try again.", contactWhatsapp: "Contact us on WhatsApp to buy", whatsappMessage: "Hello, I want to buy a DAR.EST activation key for", orActivate: "I already have a key", activationKey: "Activation key", keyPlaceholder: "Enter 56 letters and numbers", activationHint: "Never share your key. Once redeemed, it is bound to your account and cannot be transferred.", invalidKey: "Enter a valid 56-character alphanumeric key.", activationSuccess: "Subscription activated successfully. Opening your account…", activating: "Activating…", activate: "Activate subscription", proofTitle: "Confirm payment", proofIntro: "Upload the transfer receipt for your request. The subscription stays pending review and is never activated automatically.", amount: "Amount", paymentStatus: "Request status", proofSubmitted: "Receipt sent for review", proofRejected: "Action required", proofSubmittedHint: "Our team will review the receipt manually. Activation happens only after confirmation.", chooseProof: "Choose receipt image", proofFormats: "PNG, JPG or PDF — maximum 5MB", proofReading: "Reading file…", proofUploading: "Uploading receipt…", proofManualOnly: "Activation follows manual review", proofFileType: "Choose a PNG, JPG or PDF file.", proofFileSize: "The file exceeds 5MB.", proofRequestMissing: "Payment request not found.", proofReadFailed: "Could not read the file.", proofUploadFailed: "Could not upload the receipt. Please try again.", account: "Account" },
  he: { home: "דף הבית", selectedPlan: "התוכנית שנבחרה", accessDuration: "משך הגישה", keyUnique: "מפתח ייחודי לשימוש חד-פעמי", planLocked: "המפתח תקף לתוכנית זו בלבד", keyHint: "מפתח הפעלה בן 56 תווים", buyTitle: "רכישה או הפעלת מפתח", buyIntro: "לרכישת מפתח חדש, פנו אלינו ב-WhatsApp או בחרו אמצעי תשלום. אם יש לכם מפתח לתוכנית זו, הזינו אותו להפעלת המנוי.", choosePayment: "בחירת אמצעי תשלום", paymentIntro: "לאחר פתיחת קישור התשלום, הבקשה תישאר בהמתנה לאישור ידני. המנוי לא יופעל אוטומטית.", paypal: "תשלום דרך PayPal", bit: "תשלום דרך bit", paymentOpening: "מכינים את בקשת התשלום…", paymentPending: "ממתינים לאישור תשלום", paymentPendingHint: "הבקשה נרשמה. פתחו את קישור התשלום והשלימו את התשלום; ההפעלה תתבצע רק לאחר בדיקה.", paymentFailed: "לא ניתן ליצור את בקשת התשלום. נסו שוב.", contactWhatsapp: "יצירת קשר ב-WhatsApp לרכישה", whatsappMessage: "שלום, ברצוני לרכוש מפתח DAR.EST לתוכנית", orActivate: "כבר יש לי מפתח", activationKey: "מפתח הפעלה", keyPlaceholder: "הזינו 56 אותיות ומספרים", activationHint: "אין לשתף את המפתח. לאחר מימוש הוא נקשר לחשבון ואינו ניתן להעברה.", invalidKey: "הזינו מפתח אלפאנומרי תקין בן 56 תווים.", activationSuccess: "המנוי הופעל בהצלחה. החשבון ייפתח כעת.", activating: "מפעיל…", activate: "הפעלת מנוי", proofTitle: "אישור תשלום", proofIntro: "העלו את קבלת ההעברה עבור הבקשה. המנוי יישאר בבדיקה ולא יופעל אוטומטית.", amount: "סכום", paymentStatus: "סטטוס הבקשה", proofSubmitted: "הקבלה נשלחה לבדיקה", proofRejected: "נדרשת פעולה", proofSubmittedHint: "הצוות יבדוק את הקבלה ידנית. ההפעלה תתבצע רק לאחר אישור.", chooseProof: "בחירת תמונת קבלה", proofFormats: "PNG, JPG או PDF — עד 5MB", proofReading: "קורא את הקובץ…", proofUploading: "מעלה קבלה…", proofManualOnly: "ההפעלה מתבצעת לאחר בדיקה ידנית", proofFileType: "בחרו קובץ PNG, JPG או PDF.", proofFileSize: "הקובץ גדול מ־5MB.", proofRequestMissing: "בקשת התשלום לא נמצאה.", proofReadFailed: "לא ניתן לקרוא את הקובץ.", proofUploadFailed: "לא ניתן להעלות את הקבלה. נסו שוב.", account: "חשבון" },
  ru: { home: "Главная", selectedPlan: "Выбранный тариф", accessDuration: "Срок доступа", keyUnique: "Уникальный ключ, одно использование", planLocked: "Ключ действует только для этого тарифа", keyHint: "Ключ активации из 56 символов", buyTitle: "Купить или активировать ключ", buyIntro: "Чтобы купить новый ключ, свяжитесь с нами в WhatsApp или выберите способ оплаты. Если ключ для этого тарифа уже есть, введите его для активации подписки.", choosePayment: "Выберите способ оплаты", paymentIntro: "После открытия ссылки запрос останется в ожидании ручного подтверждения. Подписка не активируется автоматически.", paypal: "Оплатить через PayPal", bit: "Оплатить через bit", paymentOpening: "Подготавливаем запрос на оплату…", paymentPending: "Ожидается подтверждение оплаты", paymentPendingHint: "Запрос зарегистрирован. Откройте ссылку и завершите оплату; активация произойдет только после проверки.", paymentFailed: "Не удалось создать запрос на оплату. Попробуйте еще раз.", contactWhatsapp: "Связаться в WhatsApp для покупки", whatsappMessage: "Здравствуйте, хочу купить ключ DAR.EST для тарифа", orActivate: "У меня уже есть ключ", activationKey: "Ключ активации", keyPlaceholder: "Введите 56 букв и цифр", activationHint: "Не передавайте ключ другим. После активации он привязывается к аккаунту и не переносится.", invalidKey: "Введите корректный буквенно-цифровой ключ из 56 символов.", activationSuccess: "Подписка успешно активирована. Открываем аккаунт…", activating: "Активация…", activate: "Активировать подписку", proofTitle: "Подтверждение оплаты", proofIntro: "Загрузите квитанцию перевода для вашего запроса. Подписка останется на проверке и не активируется автоматически.", amount: "Сумма", paymentStatus: "Статус запроса", proofSubmitted: "Квитанция отправлена на проверку", proofRejected: "Требуется действие", proofSubmittedHint: "Команда проверит квитанцию вручную. Активация произойдет только после подтверждения.", chooseProof: "Выберите квитанцию", proofFormats: "PNG, JPG или PDF — до 5 МБ", proofReading: "Читаем файл…", proofUploading: "Загружаем квитанцию…", proofManualOnly: "Активация после ручной проверки", proofFileType: "Выберите файл PNG, JPG или PDF.", proofFileSize: "Размер файла превышает 5 МБ.", proofRequestMissing: "Платежный запрос не найден.", proofReadFailed: "Не удалось прочитать файл.", proofUploadFailed: "Не удалось загрузить квитанцию. Попробуйте еще раз.", account: "Аккаунт" },
  uk: { home: "Головна", selectedPlan: "Обраний тариф", accessDuration: "Термін доступу", keyUnique: "Унікальний ключ для одноразового використання", planLocked: "Ключ дійсний лише для цього тарифу", keyHint: "Ключ активації з 56 символів", buyTitle: "Придбати або активувати ключ", buyIntro: "Щоб придбати новий ключ, зв’яжіться з нами у WhatsApp або оберіть спосіб оплати. Якщо ключ для цього тарифу вже є, введіть його для активації підписки.", choosePayment: "Оберіть спосіб оплати", paymentIntro: "Після відкриття посилання запит залишиться в очікуванні ручного підтвердження. Підписку не буде активовано автоматично.", paypal: "Оплатити через PayPal", bit: "Оплатити через bit", paymentOpening: "Готуємо запит на оплату…", paymentPending: "Очікується підтвердження оплати", paymentPendingHint: "Запит зареєстровано. Відкрийте посилання й завершіть оплату; активація відбудеться лише після перевірки.", paymentFailed: "Не вдалося створити запит на оплату. Спробуйте ще раз.", contactWhatsapp: "Зв’язатися у WhatsApp для покупки", whatsappMessage: "Вітаю, хочу придбати ключ DAR.EST для тарифу", orActivate: "У мене вже є ключ", activationKey: "Ключ активації", keyPlaceholder: "Введіть 56 літер і цифр", activationHint: "Не передавайте ключ іншим. Після активації він прив’язується до облікового запису і не переноситься.", invalidKey: "Введіть коректний буквено-цифровий ключ із 56 символів.", activationSuccess: "Підписку успішно активовано. Відкриваємо обліковий запис…", activating: "Активація…", activate: "Активувати підписку", proofTitle: "Підтвердження оплати", proofIntro: "Завантажте квитанцію переказу для вашого запиту. Підписка залишиться на перевірці й не активується автоматично.", amount: "Сума", paymentStatus: "Статус запиту", proofSubmitted: "Квитанцію надіслано на перевірку", proofRejected: "Потрібна дія", proofSubmittedHint: "Команда перевірить квитанцію вручну. Активація відбудеться лише після підтвердження.", chooseProof: "Оберіть квитанцію", proofFormats: "PNG, JPG або PDF — до 5 МБ", proofReading: "Читаємо файл…", proofUploading: "Завантажуємо квитанцію…", proofManualOnly: "Активація після ручної перевірки", proofFileType: "Оберіть файл PNG, JPG або PDF.", proofFileSize: "Розмір файлу перевищує 5 МБ.", proofRequestMissing: "Платіжний запит не знайдено.", proofReadFailed: "Не вдалося прочитати файл.", proofUploadFailed: "Не вдалося завантажити квитанцію. Спробуйте ще раз.", account: "Обліковий запис" }
};
