import type { Lang } from "@/contexts/LocaleContext";

type OwnerCopy = {
  denied: string; home: string; review: string; intro: string; approve: string; reject: string; noRequests: string;
  proofUploaded: string; waiting: string; reference: string; plan: string; invoice: string; openProof: string;
  rejectionReason: string; request: string; testMode: string; testPurchase: string; subscriptions: string;
  noSubscriptions: string; noMatchingSubscriptions: string; subscriptionSearch: string; filterByStatus: string; clearFilters: string; testBadge: string; customer: string; ends: string; license: string; status: string;
  statuses: Record<string, string>; cancel: string; extend: string; confirmCancel: string; extendDays: string;
};

export const ownerCopy: Record<Lang, OwnerCopy> = {
  ar: { denied: "لا تملك صلاحية الوصول", home: "الرئيسية", review: "مراجعة الاشتراكات", intro: "اعتمد الدفع بعد مطابقة رقم العملية والخطة والفاتورة.", testMode: "وضع الاختبار", testPurchase: "إنشاء اشتراك اختباري", subscriptions: "الاشتراكات الحالية", noSubscriptions: "لا توجد اشتراكات مسجلة حالياً.", noMatchingSubscriptions: "لا توجد اشتراكات تطابق عوامل التصفية.", subscriptionSearch: "ابحث باسم العميل أو بريده", filterByStatus: "تصفية حسب الحالة", clearFilters: "مسح عوامل التصفية", testBadge: "اختبار", customer: "العميل", ends: "ينتهي", license: "المفتاح", status: "الحالة", approve: "اعتماد وإصدار المفتاح", reject: "رفض", noRequests: "لا توجد طلبات دفع للمراجعة حالياً.", proofUploaded: "تم رفع الإثبات وينتظر الطلب مراجعة المالك.", waiting: "سبب الرفض", reference: "مرجع العملية", plan: "الخطة", invoice: "الفاتورة", openProof: "فتح إثبات الدفع", rejectionReason: "سبب الرفض", request: "طلب", statuses: { all: "الكل", pending: "قيد الانتظار", pending_manual_verification: "بانتظار التحقق", approved: "معتمد", rejected: "مرفوض", active: "نشط", canceled: "ملغى", expired: "منتهي" }, cancel: "إلغاء الاشتراك", extend: "تمديد الاشتراك", confirmCancel: "هل تريد إلغاء هذا الاشتراك؟", extendDays: "أيام التمديد" },
  en: { denied: "You do not have access", home: "Home", review: "Subscription review", intro: "Approve payment after matching the transaction reference, plan, and invoice.", testMode: "Test mode", testPurchase: "Create test subscription", subscriptions: "Current subscriptions", noSubscriptions: "There are no subscriptions yet.", noMatchingSubscriptions: "No subscriptions match these filters.", subscriptionSearch: "Search customer name or email", filterByStatus: "Filter by status", clearFilters: "Clear filters", testBadge: "TEST", customer: "Customer", ends: "Ends", license: "License", status: "Status", approve: "Approve and issue key", reject: "Reject", noRequests: "There are no payment requests to review.", proofUploaded: "Proof uploaded; the request is waiting for owner review.", waiting: "Rejection reason", reference: "Transaction reference", plan: "Plan", invoice: "Invoice", openProof: "Open payment proof", rejectionReason: "Rejection reason", request: "Request", statuses: { all: "All", pending: "Pending", pending_manual_verification: "Awaiting verification", approved: "Approved", rejected: "Rejected", active: "Active", canceled: "Canceled", expired: "Expired" }, cancel: "Cancel subscription", extend: "Extend subscription", confirmCancel: "Cancel this subscription?", extendDays: "Extension days" },
  he: { denied: "אין לך הרשאת גישה", home: "דף הבית", review: "בדיקת מנויים", intro: "אשרו את התשלום לאחר התאמת האסמכתה, התוכנית והחשבונית.", testMode: "מצב בדיקה", testPurchase: "יצירת מנוי בדיקה", subscriptions: "מנויים נוכחיים", noSubscriptions: "אין עדיין מנויים.", noMatchingSubscriptions: "אין מנויים התואמים למסננים אלה.", subscriptionSearch: "חיפוש לפי שם לקוח או אימייל", filterByStatus: "סינון לפי סטטוס", clearFilters: "ניקוי מסננים", testBadge: "בדיקה", customer: "לקוח", ends: "מסתיים", license: "מפתח", status: "סטטוס", approve: "אישור והנפקת מפתח", reject: "דחייה", noRequests: "אין כרגע בקשות תשלום לבדיקה.", proofUploaded: "הוכחה הועלתה; הבקשה ממתינה לבדיקת הבעלים.", waiting: "סיבת הדחייה", reference: "אסמכתת עסקה", plan: "תוכנית", invoice: "חשבונית", openProof: "פתיחת הוכחת תשלום", rejectionReason: "סיבת הדחייה", request: "בקשה", statuses: { all: "הכול", pending: "ממתין", pending_manual_verification: "ממתין לאימות", approved: "אושר", rejected: "נדחה", active: "פעיל", canceled: "בוטל", expired: "פג תוקף" }, cancel: "ביטול מנוי", extend: "הארכת מנוי", confirmCancel: "לבטל את המנוי הזה?", extendDays: "ימי הארכה" },
  ru: { denied: "Нет доступа", home: "Главная", review: "Проверка подписок", intro: "Одобрите оплату после сверки номера операции, тарифа и счета.", testMode: "Тестовый режим", testPurchase: "Создать тестовую подписку", subscriptions: "Текущие подписки", noSubscriptions: "Подписок пока нет.", noMatchingSubscriptions: "Нет подписок, соответствующих этим фильтрам.", subscriptionSearch: "Поиск по имени или email клиента", filterByStatus: "Фильтр по статусу", clearFilters: "Сбросить фильтры", testBadge: "ТЕСТ", customer: "Клиент", ends: "Истекает", license: "Ключ", status: "Статус", approve: "Одобрить и выдать ключ", reject: "Отклонить", noRequests: "Нет платежных запросов для проверки.", proofUploaded: "Подтверждение загружено; запрос ожидает проверки владельца.", waiting: "Причина отказа", reference: "Номер операции", plan: "Тариф", invoice: "Счет", openProof: "Открыть подтверждение", rejectionReason: "Причина отказа", request: "Запрос", statuses: { all: "Все", pending: "Ожидает", pending_manual_verification: "Ожидает проверки", approved: "Одобрен", rejected: "Отклонен", active: "Активна", canceled: "Отменена", expired: "Истекла" }, cancel: "Отменить подписку", extend: "Продлить подписку", confirmCancel: "Отменить эту подписку?", extendDays: "Дни продления" },
  uk: { denied: "Немає доступу", home: "Головна", review: "Перевірка підписок", intro: "Схваліть оплату після звірки номера операції, тарифу та рахунку.", testMode: "Тестовий режим", testPurchase: "Створити тестову підписку", subscriptions: "Поточні підписки", noSubscriptions: "Підписок ще немає.", noMatchingSubscriptions: "Немає підписок, що відповідають цим фільтрам.", subscriptionSearch: "Пошук за іменем або email клієнта", filterByStatus: "Фільтр за статусом", clearFilters: "Очистити фільтри", testBadge: "ТЕСТ", customer: "Клієнт", ends: "Завершується", license: "Ключ", status: "Статус", approve: "Схвалити й видати ключ", reject: "Відхилити", noRequests: "Немає платіжних запитів для перевірки.", proofUploaded: "Підтвердження завантажено; запит очікує перевірки власника.", waiting: "Причина відмови", reference: "Номер операції", plan: "Тариф", invoice: "Рахунок", openProof: "Відкрити підтвердження", rejectionReason: "Причина відмови", request: "Запит", statuses: { all: "Усі", pending: "Очікує", pending_manual_verification: "Очікує перевірки", approved: "Схвалено", rejected: "Відхилено", active: "Активна", canceled: "Скасована", expired: "Завершена" }, cancel: "Скасувати підписку", extend: "Продовжити підписку", confirmCancel: "Скасувати цю підписку?", extendDays: "Дні продовження" }
};
